# Generated by Django 2.1.7 on 2019-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
    ]
